version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    hostname: ${DB_HOST}
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${DB_ROOT_USER}
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  testlink:
    image: docker.io/bitnami/testlink:1
    ports:
      - '${PORT}:8080'
    environment:
      - TESTLINK_DATABASE_HOST=${DB_HOST}
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=${DB_USER}
      - TESTLINK_DATABASE_NAME=${DB_NAME}
      - TESTLINK_DATABASE_PASSWORD=${DB_PASSWORD}
      - TESTLINK_USERNAME=${TESTLINK_USERNAME}
      - TESTLINK_PASSWORD=${TESTLINK_PASSWORD}
    volumes:
      - 'testlink_data:/bitnami/testlink'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
